server:
  port: 8899
spring:
  application:
    name: spring-ai-deepseek-demo
  ai:
    openai:
      api-key: your-api-key
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7