server:
  port: 8899
spring:
  application:
    name: spring-ai-deepseek-demo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.7